### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by devMEremenko**

### CODE REVIEW

**Comment by devMEremenko** [comment]
So, I can't specify links on libraries that were used even if they are my own, right?

If yes, they will be removed, but could you please explain why?

**Comment by Schemetrical** [comment]
Just for uniformity, it's been this way for everyone. It's easier at first glance to see which apple technologies were used and were accepted for scholarship.

If everyone put libraries we would see a lot of them and it would make rows long without adding too much information.

**Comment by devMEremenko** [comment]
Not a problem, I updated the tech stack

**Comment by Schemetrical** [comment]
Cool! I wish I could keep everything but I also need to keep consistency.

**Pull request merged**
